theme = "gruvbox_dark_hard"

[editor]
line-number = "absolute"
rulers = [120]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["read-only-indicator","diagnostics"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

#[editor.gutters]
#layout = ["diff","spacer","line-numbers"]
